app:
  home: TNA_HOME

server:
  port: 8006
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  connection-timeout: -1
  tomcat:
    max-http-post-size: 10485760

spring:
  datasource:
    ###### PostgreSQL Configuration #######
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${DB_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    platform: postgresql
    host: ${PG_HOST}
    port: ${PG_PORT}
    masterdb: ${DB_NAME}
  jpa:
    show-sql: false
    format-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    protocol: smtp
    test-connection: false
    host: smtp.gmail.com
    port: 587
    from: noreply@jaza-soft.com
    username: admin@jaza-soft.com
    password: arcutfrsuoduyivy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://iam-dev.jaza-soft.com/.well-known/jwks.json

  liquibase:
    enabled: true
