app:
  app-id: tna
client:
  id: client
  secret: secret
tenant:
  database:
    init-script-filename: initdb.sh
liquibase:
  tenant-changelog: 'classpath:/db/changelog-tenant.xml'
  enabled: true
  test:
    tenant-changelog: 'classpath:/db/changelog-integration-test.xml'
scheduler:
  pool-size: 10
auth-server:
  endpoint:
    base: https://iam-dev.jaza-soft.com

configuration:
  groups:
    - !com.jazasoft.mtdb.dto.ConfigGroup
      id: 'default'
      name: 'Default'

  settings:
    - !com.jazasoft.mtdb.dto.Setting
      key: 'min-marker-percent'
      name: 'Minimum Marker Percentage'
      description: ''
      value: '85'
      unit: '%'
      dataType: 'number'
      serialNo: 1
      roles: 'super_user,admin'
      groupId: 'default'
