app: 
   app-id: tna
scheduler: 
   pool-size: '10'
tenant:
   database:
      init-script-filename: initdb.sh
liquibase:
   tenant-changelog: classpath:/db/changelog-tenant.xml
   rollback-sql: rollback-sql-temp.sql
   enabled: true
iam:
   endpoint: https://iam-dev.jaza-soft.com
client:
   id: client
   secret: secret

configuration: 
   settings: 
   - !com.jazasoft.mtdb.dto.Setting
      name: Minimum Marker Percentage
      dataType: number
      description: ""
      groupId: default
      key: min-marker-percent
      roles: super_user,admin
      serialNo: 1
      unit: '%'
      value: '85'
   groups: 
   - !com.jazasoft.mtdb.dto.ConfigGroup
      id: default
      name: Default

