app:
  home: TNA_HOME

server:
  port: 8006

spring:
  datasource:
    ###### PostgreSQL Configuration #######
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tna_master
    username: razamd
    password: zahid7292
    platform: postgresql
    host: localhost
    port: 5432
    masterdb: tna_master

  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
        hbm2ddl:
          auto: none
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    protocol: smtp
    test-connection: false
    host: smtp.gmail.com
    port: 587
    from: noreply@jaza-soft.com
    username: admin@jaza-soft.com
    password: arcutfrsuoduyivy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://iam-dev.jaza-soft.com/.well-known/jwks.json

  liquibase:
    enabled: true


